# risk_table.py
# fire: "yes" = confirmed fire hazard, "maybe" = depends on material (e.g. glass bottle), "no" = no direct fire hazard
# years and alert texts are estimated values and may vary based on sources.

RISK_TABLE = {
    "Bottle": {
        "label_tr": "Bottle",
        "label": "Bottle",
        "years": "450 (plastic) - 1,000,000+ (glass)",
        "risk": "high",
        "score": 70,
        "fire": "maybe",
        "alert": "Glass poses a wildfire ignition risk via lensing; plastic introduces persistent microplastics into soil and waterways.",
        "action": "Sort and place into the appropriate glass or plastic recycling bin.",
    },
    "Bottle cap": {
        "label_tr": "Bottle Cap",
        "label": "Bottle Cap",
        "years": "450",
        "risk": "medium",
        "score": 40,
        "fire": "no",
        "alert": "Small plastic fragment that presents a choking hazard to birds and small terrestrial wildlife.",
        "action": "Place in the plastic recycling bin.",
    },
    "Can": {
        "label_tr": "Metal Can",
        "label": "Metal Can",
        "years": "200-500",
        "risk": "medium",
        "score": 50,
        "fire": "no",
        "alert": "Sharp edges present physical injury risks to wildlife and domestic animals.",
        "action": "Rinse and place in the metal recycling bin.",
    },
    "Cigarette": {
        "label_tr": "Cigarette Butt",
        "label": "Cigarette Butt",
        "years": "10-12",
        "risk": "critical",
        "score": 85,
        "fire": "yes",
        "alert": "Immediate wildfire ignition hazard in dry vegetation, alongside severe chemical toxicity to soil and runoff water.",
        "action": "Extinguish completely and dispose of in a sealed ash container; never discard on the ground.",
    },
    "Plastic bag & wrapper": {
        "label_tr": "Plastic Bag & Wrapper",
        "label": "Plastic Bag & Wrapper",
        "years": "10-1000",
        "risk": "high",
        "score": 65,
        "fire": "no",
        "alert": "High risk of entanglement and fatal intestinal blockage for foraging animals.",
        "action": "Collect and deposit in designated soft-plastic recycling collection bins.",
    },
    "Other plastic": {
        "label_tr": "Miscellaneous Plastic",
        "label": "Miscellaneous Plastic",
        "years": "20-500",
        "risk": "high",
        "score": 60,
        "fire": "no",
        "alert": "Degrades progressively into microplastics, contaminating the surrounding food web.",
        "action": "Place in the general plastic recycling bin.",
    },
    "Carton": {
        "label_tr": "Carton / Paper Box",
        "label": "Carton / Paper Box",
        "years": "2 months - 5 years",
        "risk": "low",
        "score": 20,
        "fire": "no",
        "alert": "Biodegradable, but plastic/wax-coated layers delay natural decomposition significantly.",
        "action": "Flatten and place in the paper and cardboard recycling bin.",
    },
    "Cup": {
        "label_tr": "Disposable Cup",
        "label": "Disposable Cup",
        "years": "20-50",
        "risk": "medium",
        "score": 35,
        "fire": "no",
        "alert": "Polyethylene lining prevents natural degradation and complicates standard recycling.",
        "action": "Sort based on material type into the paper or dedicated cup recycling bin.",
    },
    "Other": {
        "label_tr": "General Waste",
        "label": "General Waste",
        "years": "Unknown",
        "risk": "low",
        "score": 15,
        "fire": "no",
        "alert": "Unclassified solid waste item.",
        "action": "Refer to local municipality waste disposal and sorting guidelines.",
    },
}

DEFAULT = {
    "label_tr": "Unidentified Item",
    "label": "Unidentified Item",
    "years": "Unknown",
    "risk": "low",
    "score": 10,
    "fire": "no",
    "alert": "Unclassified object detected.",
    "action": "Inspect manually and consult local sorting regulations.",
}